name: Publish

on:
  push:
    branches: [release/1.x]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --verbosity normal

    - name: Pack
      run: dotnet pack --output artifacts --configuration Release

    - name: Push
      run: cd artifacts; dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
